// this file is auto-generated by com.qwert2603.dao_generator.GenerateDaoProcessor
package com.qwert2603.crmit_android.db.dao

import android.arch.persistence.room.Dao
import android.arch.persistence.room.Insert
import android.arch.persistence.room.OnConflictStrategy
import android.arch.persistence.room.Query
import com.qwert2603.crmit_android.db.DaoInterface
import com.qwert2603.crmit_android.entity.Section

@Dao
interface SectionDao {

    @Insert
    fun addItems(items: List<Section>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun saveItem(item: Section)

    @Query("SELECT * FROM Section WHERE id = :itemId")
    fun getItem(itemId: Long): Section

    @Query("SELECT * FROM Section WHERE name LIKE '%' || :search || '%' LIMIT :count OFFSET :offset")
    fun getItems(search: String, offset: Int, count: Int): List<Section>

    @Query("DELETE FROM Section")
    fun deleteAllItems()
}

class SectionDaoWrapper(private val SectionDao: SectionDao) : DaoInterface<Section> {
    override fun addItems(items: List<Section>) = SectionDao.addItems(items)
    override fun saveItem(item: Section) = SectionDao.saveItem(item)
    override fun getItem(itemId: Long): Section = SectionDao.getItem(itemId)
    override fun getItems(search: String, offset: Int, count: Int): List<Section> = SectionDao.getItems(search, offset, count)
    override fun deleteAllItems() = SectionDao.deleteAllItems()
}