// this file is auto-generated by com.qwert2603.dao_generator.GenerateDaoProcessor
package com.qwert2603.crmit_android.db.dao

import android.arch.persistence.room.Dao
import android.arch.persistence.room.Insert
import android.arch.persistence.room.OnConflictStrategy
import android.arch.persistence.room.Query
import com.qwert2603.crmit_android.db.DaoInterface
import com.qwert2603.crmit_android.entity.StudentFull

@Dao
interface StudentFullDao {

    @Insert
    fun addItems(items: List<StudentFull>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun saveItem(item: StudentFull)

    @Query("SELECT * FROM StudentFull WHERE id = :itemId")
    fun getItem(itemId: Long): StudentFull

    @Query("SELECT * FROM StudentFull WHERE fio LIKE '%' || :search || '%' LIMIT :count OFFSET :offset")
    fun getItems(search: String, offset: Int, count: Int): List<StudentFull>

    @Query("DELETE FROM StudentFull")
    fun deleteAllItems()
}

class StudentFullDaoWrapper(private val StudentFullDao: StudentFullDao) : DaoInterface<StudentFull> {
    override fun addItems(items: List<StudentFull>) = StudentFullDao.addItems(items)
    override fun saveItem(item: StudentFull) = StudentFullDao.saveItem(item)
    override fun getItem(itemId: Long): StudentFull = StudentFullDao.getItem(itemId)
    override fun getItems(search: String, offset: Int, count: Int): List<StudentFull> = StudentFullDao.getItems(search, offset, count)
    override fun deleteAllItems() = StudentFullDao.deleteAllItems()
}