// this file is auto-generated by com.qwert2603.dao_generator.GenerateDaoProcessor
package com.qwert2603.crmit_android.db.dao

import android.arch.persistence.room.Dao
import android.arch.persistence.room.Insert
import android.arch.persistence.room.OnConflictStrategy
import android.arch.persistence.room.Query
import com.qwert2603.crmit_android.db.DaoInterface
import com.qwert2603.crmit_android.entity.StudentBrief

@Dao
interface StudentBriefDao {

    @Insert
    fun addItems(items: List<StudentBrief>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun saveItem(item: StudentBrief)

    @Query("SELECT * FROM StudentBrief WHERE id = :itemId")
    fun getItem(itemId: Long): StudentBrief

    @Query("SELECT * FROM StudentBrief WHERE fio LIKE '%' || :search || '%' LIMIT :count OFFSET :offset")
    fun getItems(search: String, offset: Int, count: Int): List<StudentBrief>

    @Query("DELETE FROM StudentBrief")
    fun deleteAllItems()
}

class StudentBriefDaoWrapper(private val StudentBriefDao: StudentBriefDao) : DaoInterface<StudentBrief> {
    override fun addItems(items: List<StudentBrief>) = StudentBriefDao.addItems(items)
    override fun saveItem(item: StudentBrief) = StudentBriefDao.saveItem(item)
    override fun getItem(itemId: Long): StudentBrief = StudentBriefDao.getItem(itemId)
    override fun getItems(search: String, offset: Int, count: Int): List<StudentBrief> = StudentBriefDao.getItems(search, offset, count)
    override fun deleteAllItems() = StudentBriefDao.deleteAllItems()
}