// this file is auto-generated by com.qwert2603.dao_generator.GenerateDaoProcessor
package com.qwert2603.crmit_android.db.generated_dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.qwert2603.crmit_android.db.DaoInterface
import com.qwert2603.crmit_android.entity.Bot

@Dao
interface BotDao {

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun addItems(items: List<Bot>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun saveItem(item: Bot)

    @Query("SELECT * FROM Bot WHERE id = :itemId")
    fun getItem(itemId: Long): Bot?

    @Query(
        " SELECT *" +
        " FROM Bot" +
        " WHERE fio LIKE '%' || :search || '%'" +
        " ORDER BY fio" +
        " LIMIT :count" +
        " OFFSET :offset"
    )
    fun getItems(search: String, offset: Int, count: Int): List<Bot>

    @Query("DELETE FROM Bot ")
    fun deleteAllItems()

    @Query("DELETE FROM Bot")
    fun clearTable()
}

fun BotDao.wrap(): DaoInterface<Bot> = BotDaoWrapper( this)

private class BotDaoWrapper( private val botDao: BotDao) : DaoInterface<Bot> {
    override fun addItems(items: List<Bot>) = botDao.addItems(items)
    override fun saveItem(item: Bot) = botDao.saveItem(item)
    override fun getItem(itemId: Long): Bot? = botDao.getItem(itemId)
    override fun getItems(search: String, offset: Int, count: Int): List<Bot> = botDao.getItems(search, offset, count)
    override fun deleteAllItems() = botDao.deleteAllItems()
}