// this file is auto-generated by com.qwert2603.dao_generator.GenerateDaoProcessor
package com.qwert2603.crmit_android.db.generated_dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.qwert2603.crmit_android.db.DaoInterface
import com.qwert2603.crmit_android.entity.Payment

@Dao
interface PaymentDao {

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun addItems(items: List<Payment>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun saveItem(item: Payment)

    @Query("SELECT * FROM Payment WHERE id = :itemId")
    fun getItem(itemId: Long): Payment?

    @Query(
        " SELECT *" +
        " FROM Payment" +
        " WHERE groupId = :groupId AND monthNumber = :monthNumber" +
        " ORDER BY studentFio" +
        " LIMIT :count" +
        " OFFSET :offset"
    )
    fun getItems(groupId: Long, monthNumber: Int, offset: Int, count: Int): List<Payment>

    @Query("DELETE FROM Payment WHERE groupId = :groupId AND monthNumber = :monthNumber")
    fun deleteAllItems(groupId: Long, monthNumber: Int)

    @Query("DELETE FROM Payment")
    fun clearTable()
}

fun PaymentDao.wrap(groupId: Long, monthNumber: Int): DaoInterface<Payment> = PaymentDaoWrapper(groupId, monthNumber,  this)

private class PaymentDaoWrapper(private val groupId: Long, private val monthNumber: Int,  private val paymentDao: PaymentDao) : DaoInterface<Payment> {
    override fun addItems(items: List<Payment>) = paymentDao.addItems(items)
    override fun saveItem(item: Payment) = paymentDao.saveItem(item)
    override fun getItem(itemId: Long): Payment? = paymentDao.getItem(itemId)
    override fun getItems(search: String, offset: Int, count: Int): List<Payment> = paymentDao.getItems(groupId, monthNumber, offset, count)
    override fun deleteAllItems() = paymentDao.deleteAllItems(groupId, monthNumber)
}