// this file is auto-generated by com.qwert2603.dao_generator.GenerateDaoProcessor
package com.qwert2603.crmit_android.db.generated_dao

import android.arch.persistence.room.Dao
import android.arch.persistence.room.Insert
import android.arch.persistence.room.OnConflictStrategy
import android.arch.persistence.room.Query
import com.qwert2603.crmit_android.db.DaoInterface
import com.qwert2603.crmit_android.entity.Payment

@Dao
interface PaymentDao {

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun addItems(items: List<Payment>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun saveItem(item: Payment)

    @Query("SELECT * FROM Payment WHERE id = :itemId")
    fun getItem(itemId: Long): Payment?

    @Query(
        " SELECT *" +
        " FROM Payment" +
        " WHERE groupId = :groupId AND month = :month" +
        " ORDER BY studentFio" +
        " LIMIT :count" +
        " OFFSET :offset"
    )
    fun getItems(groupId: Long, month: Int, offset: Int, count: Int): List<Payment>

    @Query("DELETE FROM Payment WHERE groupId = :groupId AND month = :month")
    fun deleteAllItems(groupId: Long, month: Int)

    @Query("DELETE FROM Payment")
    fun clearTable()
}

fun PaymentDao.wrap(groupId: Long, month: Int): DaoInterface<Payment> = PaymentDaoWrapper(groupId, month,  this)

private class PaymentDaoWrapper(private val groupId: Long, private val month: Int,  private val paymentDao: PaymentDao) : DaoInterface<Payment> {
    override fun addItems(items: List<Payment>) = paymentDao.addItems(items)
    override fun saveItem(item: Payment) = paymentDao.saveItem(item)
    override fun getItem(itemId: Long): Payment? = paymentDao.getItem(itemId)
    override fun getItems(search: String, offset: Int, count: Int): List<Payment> = paymentDao.getItems(groupId, month, offset, count)
    override fun deleteAllItems() = paymentDao.deleteAllItems(groupId, month)
}