// this file is auto-generated by com.qwert2603.dao_generator.GenerateDaoProcessor
package com.qwert2603.crmit_android.db.generated_dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.qwert2603.crmit_android.db.DaoInterface
import com.qwert2603.crmit_android.entity.StudentInGroup

@Dao
interface StudentInGroupDao {

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun addItems(items: List<StudentInGroup>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun saveItem(item: StudentInGroup)

    @Query("SELECT * FROM StudentInGroup WHERE id = :itemId")
    fun getItem(itemId: Long): StudentInGroup?

    @Query(
        " SELECT *" +
        " FROM StudentInGroup" +
        " WHERE groupId = :groupId" +
        " ORDER BY studentFio" +
        " LIMIT :count" +
        " OFFSET :offset"
    )
    fun getItems(groupId: Long, offset: Int, count: Int): List<StudentInGroup>

    @Query("DELETE FROM StudentInGroup WHERE groupId = :groupId")
    fun deleteAllItems(groupId: Long)

    @Query("DELETE FROM StudentInGroup")
    fun clearTable()
}

fun StudentInGroupDao.wrap(groupId: Long): DaoInterface<StudentInGroup> = StudentInGroupDaoWrapper(groupId,  this)

private class StudentInGroupDaoWrapper(private val groupId: Long,  private val studentInGroupDao: StudentInGroupDao) : DaoInterface<StudentInGroup> {
    override fun addItems(items: List<StudentInGroup>) = studentInGroupDao.addItems(items)
    override fun saveItem(item: StudentInGroup) = studentInGroupDao.saveItem(item)
    override fun getItem(itemId: Long): StudentInGroup? = studentInGroupDao.getItem(itemId)
    override fun getItems(search: String, offset: Int, count: Int): List<StudentInGroup> = studentInGroupDao.getItems(groupId, offset, count)
    override fun deleteAllItems() = studentInGroupDao.deleteAllItems(groupId)
}