// this file is auto-generated by com.qwert2603.dao_generator.GenerateDaoProcessor
package com.qwert2603.crmit_android.db.generated_dao

import android.arch.persistence.room.Dao
import android.arch.persistence.room.Insert
import android.arch.persistence.room.OnConflictStrategy
import android.arch.persistence.room.Query
import com.qwert2603.crmit_android.db.DaoInterface
import com.qwert2603.crmit_android.entity.Teacher

@Dao
interface TeacherDao {

    @Insert
    fun addItems(items: List<Teacher>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun saveItem(item: Teacher)

    @Query("SELECT * FROM Teacher WHERE id = :itemId")
    fun getItem(itemId: Long): Teacher

    @Query("SELECT * FROM Teacher WHERE fio LIKE '%' || :search || '%' LIMIT :count OFFSET :offset")
    fun getItems(search: String, offset: Int, count: Int): List<Teacher>

    @Query("DELETE FROM Teacher")
    fun deleteAllItems()
}

fun TeacherDao.wrap() = TeacherDaoWrapper(this)

class TeacherDaoWrapper(private val teacherDao: TeacherDao) : DaoInterface<Teacher> {
    override fun addItems(items: List<Teacher>) = teacherDao.addItems(items)
    override fun saveItem(item: Teacher) = teacherDao.saveItem(item)
    override fun getItem(itemId: Long): Teacher = teacherDao.getItem(itemId)
    override fun getItems(search: String, offset: Int, count: Int): List<Teacher> = teacherDao.getItems(search, offset, count)
    override fun deleteAllItems() = teacherDao.deleteAllItems()
}